version: "3"
services:
  backend:
    build: ./backend
    container_name: 'turismo_api_back'
    command: sh -c 'npm install; npm start'
    ports:
      - '3002:3002'
    volumes:
      - ./backend:/backend
    depends_on:
      - "db-turismo"

  db-turismo:
    container_name: 'db_redis_turismo'
    image: redis
    ports:
      - "6380:6379"

  fronted:
    build: ./fronted
    container_name: 'turismo_api_front'
    command: sh -c 'npm install; npm start'
    ports:
      - '3000:3000'
    volumes:
      - ./fronted:/fronted
    depends_on:
      - "backend"
    stdin_open: true
    tty: true

    