# Script de Inicialización (Seed) de Base de Datos
# Este archivo se encarga de poblar la base de datos de MongoDB con datos iniciales (40 superhéroes).

from pymongo import MongoClient

# Conexión a la base de datos MongoDB (por defecto en localhost)
client = MongoClient("mongodb://localhost:27017/superheroes_db")
db = client.get_default_database()
superheroes_collection = db["superheroes"]


superheroes = [
    # Marvel (20)
    {"name": "Spider-Man", "real_name": "Peter Parker", "year": 1962, "house": "Marvel", "bio": "Mordido por una araña radiactiva, Peter Parker obtuvo habilidades arácnidas y combate el crimen en Nueva York.", "equipment": "Lanzatelarañas", "images": ["https://upload.wikimedia.org/wikipedia/en/2/21/Web_of_Spider-Man_Vol_1_129-1.png"]},
    {"name": "Iron Man", "real_name": "Tony Stark", "year": 1963, "house": "Marvel", "bio": "Multimillonario genio que construyó una armadura de alta tecnología para combatir el mal.", "equipment": "Armadura de Iron Man, Repulsores", "images": ["https://upload.wikimedia.org/wikipedia/en/4/47/Iron_Man_%28circa_2018%29.png"]},
    {"name": "Capitán América", "real_name": "Steve Rogers", "year": 1941, "house": "Marvel", "bio": "Un joven frágil mejorado hasta la cima de la perfección humana por un suero experimental.", "equipment": "Escudo de Vibranium", "images": ["https://upload.wikimedia.org/wikipedia/en/9/91/CaptainAmerica109.jpg"]},
    {"name": "Thor", "real_name": "Thor Odinson", "year": 1962, "house": "Marvel", "bio": "El Dios Asgardiano del Trueno, que empuña el martillo encantado Mjolnir.", "equipment": "Mjolnir", "images": ["https://upload.wikimedia.org/wikipedia/en/3/3c/Thor_marvel.jpg"]},
    {"name": "Hulk", "real_name": "Bruce Banner", "year": 1962, "house": "Marvel", "bio": "Un científico expuesto a radiación gamma, transformándose en un gigante monstruo de rabia cuando se enfada.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/a/aa/Hulk_%28circa_2019%29.png"]},
    {"name": "Viuda Negra", "real_name": "Natasha Romanoff", "year": 1964, "house": "Marvel", "bio": "Una antigua asesina y espía de la KGB altamente entrenada.", "equipment": "Brazaletes de la Viuda", "images": ["https://upload.wikimedia.org/wikipedia/en/e/e9/Black_Widow_%28Natasha_Romanova%29.png"]},
    {"name": "Doctor Strange", "real_name": "Stephen Strange", "year": 1963, "house": "Marvel", "bio": "Un brillante pero arrogante cirujano que se convierte en el Hechicero Supremo tras un accidente automovilístico.", "equipment": "Capa de Levitación, Ojo de Agamotto", "images": ["https://upload.wikimedia.org/wikipedia/en/4/4f/Doctor_Strange_Vol_4_2_Cover.jpg"]},
    {"name": "Pantera Negra", "real_name": "T'Challa", "year": 1966, "house": "Marvel", "bio": "Rey de la avanzada nación africana de Wakanda, con habilidades sobrehumanas gracias a la Hierba en Forma de Corazón.", "equipment": "Traje de Vibranium", "images": ["https://upload.wikimedia.org/wikipedia/en/9/9f/Black_Panther_OS_Vol_1_2.png"]},
    {"name": "Wolverine", "real_name": "Logan", "year": 1974, "house": "Marvel", "bio": "Un mutante con sentidos animales agudos, capacidades físicas mejoradas y un factor de curación.", "equipment": "Garras de Adamantium", "images": ["https://upload.wikimedia.org/wikipedia/en/c/c8/Marvelwolverine.jpg"]},
    {"name": "Capitana Marvel", "real_name": "Carol Danvers", "year": 1968, "house": "Marvel", "bio": "Una piloto de la Fuerza Aérea cuyo ADN fue fusionado con el de un Kree, otorgándole un poder sobrehumano.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/8/85/Captain_Marvel_Vol_9_8.jpg"]},
    {"name": "Daredevil", "real_name": "Matt Murdock", "year": 1964, "house": "Marvel", "bio": "Un abogado ciego cuyos otros sentidos están aumentados a niveles sobrehumanos.", "equipment": "Bastón de combate", "images": ["https://upload.wikimedia.org/wikipedia/en/b/b2/Daredevil_%28Marvel_Comics%29.png"]},
    {"name": "Deadpool", "real_name": "Wade Wilson", "year": 1991, "house": "Marvel", "bio": "Un mercenario desfigurado y mentalmente inestable con la habilidad sobrehumana de un factor de curación acelerado.", "equipment": "Katanas, Armas de fuego", "images": ["https://upload.wikimedia.org/wikipedia/en/1/1c/Deadpool_Vol_9_1_Skan_Srisuwan_Variant.jpg"]},
    {"name": "Bruja Escarlata", "real_name": "Wanda Maximoff", "year": 1964, "house": "Marvel", "bio": "Una mutante con la capacidad de alterar la realidad y la probabilidad.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/9/90/Scarlet_Witch_Vol_3_1.jpg"]},
    {"name": "Visión", "real_name": "", "year": 1968, "house": "Marvel", "bio": "Un androide creado por Ultron para destruir a los Vengadores, que en su lugar se volvió contra su creador.", "equipment": "Gema de la Mente", "images": ["https://upload.wikimedia.org/wikipedia/en/1/10/Vision_%28Marvel_Comics%29.png"]},
    {"name": "Ant-Man", "real_name": "Scott Lang", "year": 1979, "house": "Marvel", "bio": "Un maestro ladrón que asumió el manto de Ant-Man, capaz de encogerse en tamaño pero aumentar en fuerza.", "equipment": "Traje de Ant-Man, Partículas Pym", "images": ["https://upload.wikimedia.org/wikipedia/en/1/15/Ant-Man_%28Scott_Lang%29.png"]},
    {"name": "Ojo de Halcón", "real_name": "Clint Barton", "year": 1964, "house": "Marvel", "bio": "Un maestro arquero y ex artista de circo.", "equipment": "Arco, Flechas Trucadas", "images": ["https://upload.wikimedia.org/wikipedia/en/9/99/Hawkeye_%28Clinton_Barton%29.png"]},
    {"name": "Groot", "real_name": "Groot", "year": 1960, "house": "Marvel", "bio": "Una criatura extraterrestre y sensible con aspecto de árbol.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/0/07/Groot_%28Marvel_Comics_character%29.jpg"]},
    {"name": "Rocket Raccoon", "real_name": "Rocket", "year": 1976, "house": "Marvel", "bio": "Un mapache antropomórfico inteligente, experto tirador y maestro estratega.", "equipment": "Cañones Láser", "images": ["https://upload.wikimedia.org/wikipedia/en/2/22/Rocket_Raccoon_1.jpg"]},
    {"name": "Star-Lord", "real_name": "Peter Quill", "year": 1976, "house": "Marvel", "bio": "Mitad humano, mitad celestial y líder de los Guardianes de la Galaxia.", "equipment": "Blasters Cuádruples", "images": ["https://upload.wikimedia.org/wikipedia/en/6/60/Star-Lord_%28Peter_Quill%29.jpg"]},
    {"name": "Thanos", "real_name": "Thanos", "year": 1973, "house": "Marvel", "bio": "Un poderoso señor de la guerra Titán obsesionado con la muerte y el equilibrio cósmico.", "equipment": "Guantelete del Infinito", "images": ["https://upload.wikimedia.org/wikipedia/en/9/90/Thanos_%28Marvel_Comics_character%29.png"]},

    # DC (20)
    {"name": "Superman", "real_name": "Clark Kent", "year": 1938, "house": "DC", "bio": "El último hijo de Krypton, criado en la Tierra con poderes divinos.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/3/35/Supermanflying.png", "https://upload.wikimedia.org/wikipedia/en/c/c5/Superman_Action_Comics_Vol_1_1000.png"]},
    {"name": "Batman", "real_name": "Bruce Wayne", "year": 1939, "house": "DC", "bio": "Un filántropo multimillonario que combate el crimen en Ciudad Gótica usando intelecto, aparatos y miedo.", "equipment": "Batarangs, Batmóvil, Cinturón de Utilidades", "images": ["https://upload.wikimedia.org/wikipedia/en/c/c7/Batman_Infobox.jpg", "https://upload.wikimedia.org/wikipedia/en/a/a8/Batman_Vol_3_86_Cover.jpg"]},
    {"name": "Mujer Maravilla", "real_name": "Diana Prince", "year": 1941, "house": "DC", "bio": "Princesa de las Amazonas, armada con habilidades sobrehumanas y entrenamiento de combate.", "equipment": "Lazo de la Verdad, Brazaletes de Sumisión", "images": ["https://upload.wikimedia.org/wikipedia/en/9/93/Wonder_Woman.jpg"]},
    {"name": "Flash", "real_name": "Barry Allen", "year": 1956, "house": "DC", "bio": "Un científico forense que obtuvo el poder de la súper velocidad después de ser alcanzado por un rayo.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/f/fe/The_Flash_%28Barry_Allen%29.png"]},
    {"name": "Aquaman", "real_name": "Arthur Curry", "year": 1941, "house": "DC", "bio": "El gobernante telepático de la Atlántida y los océanos de la Tierra.", "equipment": "Tridente de Neptuno", "images": ["https://upload.wikimedia.org/wikipedia/en/0/0a/Aquaman_issue_1%2C_the_new_52.jpg"]},
    {"name": "Linterna Verde", "real_name": "Hal Jordan", "year": 1959, "house": "DC", "bio": "Un piloto de pruebas elegido por un anillo cósmico para servir en una fuerza policial intergaláctica.", "equipment": "Anillo de Poder", "images": ["https://upload.wikimedia.org/wikipedia/en/1/1a/Green_Lantern_%28Hal_Jordan%29.jpg"]},
    {"name": "Cyborg", "real_name": "Victor Stone", "year": 1980, "house": "DC", "bio": "Un ex atleta que se convirtió en un organismo cibernético después de un trágico accidente.", "equipment": "Mejoras cibernéticas", "images": ["https://upload.wikimedia.org/wikipedia/en/7/74/Cyborg_%28Victor_Stone%29.png"]},
    {"name": "Flecha Verde", "real_name": "Oliver Queen", "year": 1941, "house": "DC", "bio": "Un playboy adinerado que utiliza sus habilidades como maestro arquero para combatir el crimen.", "equipment": "Arco, Flechas Trucadas", "images": ["https://upload.wikimedia.org/wikipedia/en/6/6b/Green_Arrow_Vol_6_1.jpg"]},
    {"name": "Shazam", "real_name": "Billy Batson", "year": 1940, "house": "DC", "bio": "Un niño que puede transformarse en un superhéroe adulto mágico al decir la palabra '¡Shazam!'.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/2/29/Shazam_%28Captain_Marvel%29.png"]},
    {"name": "Detective Marciano", "real_name": "J'onn J'onzz", "year": 1955, "house": "DC", "bio": "Un humanoide extraterrestre de piel verde del planeta Marte.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/c/cb/Martian_Manhunter.png"]},
    {"name": "Nightwing", "real_name": "Dick Grayson", "year": 1984, "house": "DC", "bio": "El Robin original, que creció y adoptó una nueva identidad de superhéroe.", "equipment": "Bastones Escrima", "images": ["https://upload.wikimedia.org/wikipedia/en/9/91/Nightwing_Rebirth.jpg"]},
    {"name": "Supergirl", "real_name": "Kara Zor-El", "year": 1959, "house": "DC", "bio": "La prima de Superman y una de las últimas kryptonianas sobrevivientes.", "equipment": "", "images": ["https://upload.wikimedia.org/wikipedia/en/4/41/Supergirl_Vol_7_1.png"]},
    {"name": "Batgirl", "real_name": "Barbara Gordon", "year": 1967, "house": "DC", "bio": "La hija del comisionado de policía de Ciudad Gótica, que opera como justiciera.", "equipment": "Batarangs, Cinturón de Utilidades", "images": ["https://upload.wikimedia.org/wikipedia/en/3/3d/Batgirl_DC_Comics.png"]},
    {"name": "El Guasón", "real_name": "Desconocido", "year": 1940, "house": "DC", "bio": "Un supervillano psicópata y el archienemigo de Batman.", "equipment": "Zumbador de alegría, Cartas de juego afiladas como navajas", "images": ["https://upload.wikimedia.org/wikipedia/en/9/98/Joker_%28DC_Comics_character%29_art.jpg"]},
    {"name": "Harley Quinn", "real_name": "Harleen Quinzel", "year": 1992, "house": "DC", "bio": "Una ex psiquiatra que se enamoró del Guasón y se convirtió en su compañera.", "equipment": "Mazo Gigante, Bate de Béisbol", "images": ["https://upload.wikimedia.org/wikipedia/en/c/ce/Harley_Quinn_Vol_3_43.png"]},
    {"name": "Lex Luthor", "real_name": "Lex Luthor", "year": 1940, "house": "DC", "bio": "Un multimillonario enloquecido por el poder, científico talentoso y el archienemigo de Superman.", "equipment": "Traje de Batalla", "images": ["https://upload.wikimedia.org/wikipedia/en/b/b6/Lex_Luthor_Action_Comics_1050.jpg"]},
    {"name": "Darkseid", "real_name": "Uxas", "year": 1970, "house": "DC", "bio": "El tiránico gobernante del planeta Apokolips, cuyo objetivo final es conquistar el universo.", "equipment": "Rayos Omega", "images": ["https://upload.wikimedia.org/wikipedia/en/5/5e/Darkseid.jpg"]},
    {"name": "Gatúbela", "real_name": "Selina Kyle", "year": 1940, "house": "DC", "bio": "Una maestra ladrona que es una adversaria frecuente e interés amoroso de Batman.", "equipment": "Látigo", "images": ["https://upload.wikimedia.org/wikipedia/en/4/48/Catwoman_Vol_5_1_Cover.jpg"]},
    {"name": "Hiedra Venenosa", "real_name": "Pamela Isley", "year": 1966, "house": "DC", "bio": "Una botánica que se convirtió en maestra de las plantas, utilizándolas para el ecoterrorismo.", "equipment": "Feromonas, Control de plantas", "images": ["https://upload.wikimedia.org/wikipedia/en/5/5a/Poison_Ivy.png"]},
    {"name": "Bane", "real_name": "Desconocido", "year": 1993, "house": "DC", "bio": "Un convicto fugado de una prisión isleña, conocido por romperle la espalda a Batman.", "equipment": "Arnés de Venom", "images": ["https://upload.wikimedia.org/wikipedia/en/e/e1/Bane_Batman_Vol_3_18.png"]},
]

if __name__ == "__main__":
    # 1. Limpiamos la colección para evitar duplicados si se ejecuta múltiples veces
    superheroes_collection.drop()
    print("Colección existente eliminada.")
    
    # 2. Insertamos la lista completa de superhéroes
    result = superheroes_collection.insert_many(superheroes)
    print(f"Se insertaron {len(result.inserted_ids)} superhéroes.")
